apiVersion: v1 
kind: Service
metadata:
  name: mysql-headless
  namespace: expense 
spec:
  clusterIP: None # for headless service there is no cluster IP
  selector: 
    project: expense
    component: mysql 
    tier: db 
  ports:
  - protocol: TCP
    port: 3306 # service port 
    targetPort: 3306
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: expense
spec:
  selector: 
    project: expense
    component: mysql 
    tier: db 
  ports:
  - protocol: TCP
    port: 3306 # service port 
    targetPort: 3306
---
apiVersion: app/v1
kind: StatefulSet
metadata:
  name: mysql 
  namespace: expense
spec:
  selector:
    matchLabels:
      project: expense
      component: mysql 
      tier: db 
  serviceName: "mysql-headless"
  replicas: 2
  template:
    metadata:
      labels:
        project: expense
        component: mysql 
        tier: db 
    spec:
      containers:
      - name: mysql
        image: ramak8sgcp/mysql:v1
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
